/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilyriadz.database.util;

import ilyriadz.database.DatabaseManager;
import ilyriadz.database.H2Database;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static DatabaseManager dbm;
    
    static
    {
        try {
            dbm = new H2Database();
            dbm.connect("./books");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        var paneldata = DatabaseGutil.generatePanelData(Book.class);
        this.getContentPane().add(new JScrollPane(paneldata.getPanel()), 
            BorderLayout.NORTH);
        
        jScrollPane1.setMaximumSize(new Dimension(Integer.MAX_VALUE, 300));
        
        JButton insert = new JButton("insert");
        insert.addActionListener(DatabaseGutil.generateInsertAction(
            dbm, "books", paneldata, Book.class, () -> {
            try {
                jTable1.setModel(DatabaseGutil.generateTableModel(dbm, "books", "", Book.class));
                JOptionPane.showMessageDialog(this, "Data inserted successfully",
                        "Message", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | NoSuchFieldException | 
                IllegalArgumentException | IllegalAccessException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.toString(), "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            }));
        
        paneldata.getPanel().add(insert);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        try{
            jTable1 = ilyriadz.database.util.DatabaseGutil.generateTable(dbm, "books", "", Book.class);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        }
        catch (Exception ex)
        {

        }
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(537, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
